image: node:10.22.0
pages:
  cache:
    paths:
      - node_modules/
  script:
    - pnpm install # npm install
    - pnpm run docs:build # npm run docs:build
  artifacts:
    paths:
      - public
  only:
    - master